@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.example.todoapp.ui.TodoListFragment",
  "extensionCallbackMethod": ".png" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1322970774 { 
   	label=example
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_297925527 { 
   	label=todoapp
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   EditTodoFragment1920140840[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)EditTodoFragment</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   cal: Calendar [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   cancelButton: Button [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   categorySpinner: Spinner [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   currentTodo: Todo [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   detailEditText: TextInputEditText [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   dueDate: Date [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   dueDateInput: Button [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   editButton: Button [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   isCompleteSwitch: Switch [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   prioritySpinner: Spinner [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   titleEditText: TextInputEditText [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   todoModel: TodoModel [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ newInstance(todoId: UUID): EditTodoFragment</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCreate(savedInstanceState: Bundle)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCreateView(inflater: LayoutInflater, container: ViewGroup, savedInstanceState: Bundle): View</TD></TR>
<TR><TD ALIGN="LEFT" >+ onDateSelected(year: int, month: int, day: int)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Todo79788479[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Todo</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   category: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   completedAt: Date [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   createdAt: Date [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   detail: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   dueDate: Date [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: UUID [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   isComplete: Boolean [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   lastUpdated: Date [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   priority: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   title: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TodoAdapter1920140840[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TodoAdapter</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   context: Context [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   data: List&lt;Todo&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   todoModel: TodoModel [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ onBindViewHolder(holder: ViewHolder, position: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCreateViewHolder(parent: ViewGroup, viewType: int): ViewHolder</TD></TR>
<TR><TD ALIGN="LEFT" >+ openDialog(view: View, id: UUID)</TD></TR>
<TR><TD ALIGN="LEFT" >+ submitData(data: List&lt;Todo&gt;)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TodoDao_Impl79788479[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TodoDao_Impl</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   __db: RoomDatabase [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   __insertionAdapterOfTodo: EntityInsertionAdapter&lt;Todo&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   __preparedStmtOfDelete: SharedSQLiteStatement [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   __preparedStmtOfDeleteAll: SharedSQLiteStatement [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   __updateAdapterOfTodo: EntityDeletionOrUpdateAdapter&lt;Todo&gt; [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ delete(id: UUID)</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteAll()</TD></TR>
<TR><TD ALIGN="LEFT" >+ getTodoById(id: UUID): LiveData&lt;Todo&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ insert(todo: Todo)</TD></TR>
<TR><TD ALIGN="LEFT" >+ update(todo: Todo)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TodoDatabase79788479[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TodoDatabase</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># getDatabase(context: Context): TodoDatabase</TD></TR>
<TR><TD ALIGN="LEFT" >+ todoDao(): TodoDao</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TodoListFragment1920140840[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TodoListFragment</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   adapter: TodoAdapter [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   addTodoButton: FloatingActionButton [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   completeCount: TextView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   incompleteCount: TextView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   recyclerView: RecyclerView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   todoModel: TodoModel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   totalCount: TextView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   view: View [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ newInstance(): TodoListFragment</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCreate(savedInstanceState: Bundle)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCreateOptionsMenu(menu: Menu, inflater: MenuInflater)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCreateView(inflater: LayoutInflater, container: ViewGroup, savedInstanceState: Bundle): View</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TodoModel1920140840[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TodoModel</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   repository: TodoRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   todosList: LiveData&lt;List&lt;Todo&gt;&gt; [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># addTodo(todo: Todo)</TD></TR>
<TR><TD ALIGN="LEFT" ># delete(id: UUID)</TD></TR>
<TR><TD ALIGN="LEFT" ># getTodo(id: UUID): LiveData&lt;Todo&gt;</TD></TR>
<TR><TD ALIGN="LEFT" ># updateTodo(todo: Todo)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TodoPagerActivity1920140840[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TodoPagerActivity</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   todoModel: TodoModel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   todosList: List&lt;Todo&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   viewPager: ViewPager2 [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ makeIntent(context: Context, todoId: UUID): Intent</TD></TR>
<TR><TD ALIGN="LEFT" ># onCreate(savedInstanceState: Bundle)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TodoRepository79788479[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TodoRepository</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   database: TodoDatabase [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   todoDao: TodoDao [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   todos: LiveData&lt;List&lt;Todo&gt;&gt; [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ delete(id: UUID)</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteAll()</TD></TR>
<TR><TD ALIGN="LEFT" >+ getTodo(id: UUID): LiveData&lt;Todo&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ insert(todo: Todo)</TD></TR>
<TR><TD ALIGN="LEFT" >+ update(todo: Todo)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ViewHolder2009174797[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ViewHolder</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   completeColor: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   createdDateTextView: TextView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   deleteButton: ImageButton [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   detailTextView: TextView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   dueDateTextView: TextView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   editButton: ImageButton [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   incompleteColor: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   priorityTextView: TextView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   titleTextView: TextView [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ bind(todo: Todo)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
TodoAdapter1920140840 -> Todo79788479[label="data
[0..*]"];
TodoAdapter1920140840 -> TodoModel1920140840[label="todoModel
[0..1]"];
TodoAdapter1920140840 -> ViewHolder2009174797[label="onBindViewHolder() -> bind()"];
TodoListFragment1920140840 -> TodoAdapter1920140840[label="adapter
[0..1]"];
TodoListFragment1920140840 -> TodoModel1920140840[label="todoModel
[0..1]"];
TodoModel1920140840 -> Todo79788479[label="todosList
[0..1]"];
TodoModel1920140840 -> TodoRepository79788479[label="repository
[0..1]"];
TodoRepository79788479 -> Todo79788479[label="todos
[0..1]"];
TodoRepository79788479 -> TodoDao_Impl79788479[arrowhead=none];
TodoRepository79788479 -> TodoDatabase79788479[label="database
[0..1]"];
ViewHolder2009174797 -> EditTodoFragment1920140840[label="bind() -> newInstance()"];
ViewHolder2009174797 -> TodoAdapter1920140840[label="bind() -> openDialog()"];
ViewHolder2009174797 -> TodoPagerActivity1920140840[label="bind() -> makeIntent()"];
    
}
@enduml